name: Run tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout code          
          uses: actions/checkout@v4
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v3
          with:
            # Semantic version range syntax or exact version of a dotnet version
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore

        - name: Build project
          run: dotnet build --no-restore

        - name: Run tests
          run: dotnet test --no-build --verbosity normal